# note: added some packages through pip install
# and did a `pre-commit install` http://pre-commit.com/
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v0.9.2
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-yaml
      - id: debug-statements
      - id: flake8
        args: [--max-line-length=120, --ignore=E402]
  - repo: git://github.com/upjohnc/precommit-todo-check
    rev: 1.3.0
    hooks:
      - id: python-todo-check
        args: ['--skip=config/log_config.py, dags/GoogleAdWords/AdWordsHelper.py,  dags/GoogleAnalytics/GaHelperRoutines.py, dags/GoogleAnalytics/GaHelperRoutines_old.py, ManualExtract/AdWordsHelper.py,dags/BingAds/BingAdsGeoHelper.py,dags/GoogleAdWords/AdWordsGeoHelper.py,dags/GoogleAdWords/AdWordsHelper-test.py,dags/GoogleAdWords/AdWordsTrafficByHelper.py,dags/GoogleAnalytics/GaHelperRoutines_pre_v15.py']
  - repo: git://github.com/upjohnc/precommit_mccabe_complexity
    rev: 0.13.0
    hooks:
      - id: mccabe-complexity
        args: ['--base_branch=master']
